[[redirects]]
  from = "/"
  to = "/fr"
  status = 301
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 301
  force = true
  conditions = {Language = ["es"]}
